server:
  port: 6671
spring:
  application:
    name: panda-config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiaweiwang3306/panda.git
          default-label: ${spring.profiles.active}
---
spring:
  profiles: dev
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
---
spring:
  profiles: prod
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

